/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Equipo1
 */
public class PaymentForm extends javax.swing.JFrame {

    /**
     * Creates new form PaymentForm
     */
    public PaymentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAbsoluteContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LbConceptoDePago = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LbTipoDeBien = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LbIdDelEvento = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LbImporte = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LbFecha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LbHora = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PanelPaymentForm = new javax.swing.JPanel();
        btnMetodoOpenPay = new javax.swing.JButton();
        btnMetodoOxxo = new javax.swing.JButton();
        btnCambiarEstilo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment");

        panelAbsoluteContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagar"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Pagar ahora");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Concepto de pago:");

        LbConceptoDePago.setText("concepto");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tipo de bien:");

        LbTipoDeBien.setText("tipo de bien");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("ID del evento:");

        LbIdDelEvento.setText("id del evento");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Importe del servicio:");

        LbImporte.setText("importe");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Fecha de adjudicación:");

        LbFecha.setText("fecha de adjudicacion");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Hora de adjudicación:");

        LbHora.setText("hora de adjudicacion");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Seleccione un método de pago:");

        javax.swing.GroupLayout PanelPaymentFormLayout = new javax.swing.GroupLayout(PanelPaymentForm);
        PanelPaymentForm.setLayout(PanelPaymentFormLayout);
        PanelPaymentFormLayout.setHorizontalGroup(
            PanelPaymentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );
        PanelPaymentFormLayout.setVerticalGroup(
            PanelPaymentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        btnMetodoOpenPay.setText("OpenPay");

        btnMetodoOxxo.setText("Oxxo");

        btnCambiarEstilo.setText("Cambiar estilo");

        javax.swing.GroupLayout panelAbsoluteContainerLayout = new javax.swing.GroupLayout(panelAbsoluteContainer);
        panelAbsoluteContainer.setLayout(panelAbsoluteContainerLayout);
        panelAbsoluteContainerLayout.setHorizontalGroup(
            panelAbsoluteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAbsoluteContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAbsoluteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAbsoluteContainerLayout.createSequentialGroup()
                        .addGroup(panelAbsoluteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAbsoluteContainerLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnMetodoOxxo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(panelAbsoluteContainerLayout.createSequentialGroup()
                                .addGroup(panelAbsoluteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAbsoluteContainerLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(268, 268, 268))
                                    .addGroup(panelAbsoluteContainerLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(panelAbsoluteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAbsoluteContainerLayout.createSequentialGroup()
                                                .addGroup(panelAbsoluteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(LbConceptoDePago)
                                                    .addComponent(LbTipoDeBien)
                                                    .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(panelAbsoluteContainerLayout.createSequentialGroup()
                                                .addGroup(panelAbsoluteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(LbIdDelEvento)
                                                    .addComponent(jLabel14))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGroup(panelAbsoluteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbFecha)
                                    .addComponent(LbHora)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(LbImporte)
                                    .addComponent(btnCambiarEstilo))))
                        .addGap(61, 61, 61))
                    .addComponent(PanelPaymentForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(panelAbsoluteContainerLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnMetodoOpenPay, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAbsoluteContainerLayout.setVerticalGroup(
            panelAbsoluteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAbsoluteContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAbsoluteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnCambiarEstilo))
                .addGap(18, 18, 18)
                .addGroup(panelAbsoluteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAbsoluteContainerLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbConceptoDePago)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbTipoDeBien))
                    .addGroup(panelAbsoluteContainerLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbFecha)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbHora)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAbsoluteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAbsoluteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbIdDelEvento)
                    .addComponent(LbImporte))
                .addGap(58, 58, 58)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAbsoluteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMetodoOpenPay, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMetodoOxxo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PanelPaymentForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsoluteContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsoluteContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLbConceptoDePago() {
        return LbConceptoDePago;
    }

    public void setLbConceptoDePago(JLabel LbConceptoDePago) {
        this.LbConceptoDePago = LbConceptoDePago;
    }

    public JLabel getLbFecha() {
        return LbFecha;
    }

    public void setLbFecha(JLabel LbFecha) {
        this.LbFecha = LbFecha;
    }

    public JLabel getLbHora() {
        return LbHora;
    }

    public void setLbHora(JLabel LbHora) {
        this.LbHora = LbHora;
    }

    public JLabel getLbIdDelEvento() {
        return LbIdDelEvento;
    }

    public void setLbIdDelEvento(JLabel LbIdDelEvento) {
        this.LbIdDelEvento = LbIdDelEvento;
    }

    public JLabel getLbImporte() {
        return LbImporte;
    }

    public void setLbImporte(JLabel LbImporte) {
        this.LbImporte = LbImporte;
    }

    public JLabel getLbTipoDeBien() {
        return LbTipoDeBien;
    }

    public void setLbTipoDeBien(JLabel LbTipoDeBien) {
        this.LbTipoDeBien = LbTipoDeBien;
    }

    public JButton getBtnMetodoOpenPay() {
        return btnMetodoOpenPay;
    }

    public void setBtnMetodoOpenPay(JButton btnMetodoOpenPay) {
        this.btnMetodoOpenPay = btnMetodoOpenPay;
    }

    public JButton getBtnMetodoOxxo() {
        return btnMetodoOxxo;
    }

    public void setBtnMetodoOxxo(JButton btnMetodoOxxo) {
        this.btnMetodoOxxo = btnMetodoOxxo;
    }

    public JPanel getPanelPaymentForm() {
        return PanelPaymentForm;
    }

    public void setPanelPaymentForm(JPanel PanelPaymentForm) {
        this.PanelPaymentForm = PanelPaymentForm;
    }

    public JPanel getPanelAbsoluteContainer() {
        return panelAbsoluteContainer;
    }

    public void setPanelAbsoluteContainer(JPanel panelAbsoluteContainer) {
        this.panelAbsoluteContainer = panelAbsoluteContainer;
    }

    public JButton getBtnCambiarEstilo() {
        return btnCambiarEstilo;
    }

    public void setBtnCambiarEstilo(JButton btnCambiarEstilo) {
        this.btnCambiarEstilo = btnCambiarEstilo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbConceptoDePago;
    private javax.swing.JLabel LbFecha;
    private javax.swing.JLabel LbHora;
    private javax.swing.JLabel LbIdDelEvento;
    private javax.swing.JLabel LbImporte;
    private javax.swing.JLabel LbTipoDeBien;
    private javax.swing.JPanel PanelPaymentForm;
    private javax.swing.JButton btnCambiarEstilo;
    private javax.swing.JButton btnMetodoOpenPay;
    private javax.swing.JButton btnMetodoOxxo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelAbsoluteContainer;
    // End of variables declaration//GEN-END:variables
}
